### ISSUE TITLE
cURL error 60: SSL certificate problem

### ISSUE THREAD

**Issue by alfikridotname** [virusphp/bridging-bpjs#8]
Saya sudah coba menggunakan library ini... tetapi ada kendala di SSL certificate  problem. 
berikut response dari API BPJSnya
"metaData" => array:2 [
    "code" => 0
    "message" => "cURL error 60: SSL certificate problem: unable to get local issuer certificate (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://apijkn-dev.bpjs-kesehatan.go.id/vclaim-rest-dev/referensi/faskes/ikur/1"
  ]
  "response" => null

**Comment by virusphp** [comment]
@alfikridotname Wah terimakasih mas sudah menggunakan library ini ok mas saya coba bantu permasalahanya 
Untuk php yang  di pakai versi brapa ya mas

**Comment by virusphp** [comment]
untuk penggunakan dengan erorr `cURL error 60: SSL certificate problem: unable to get local issuer certificate (see https://curl.haxx.se/libcurl/c/libcurl-errors.html`

biasya extensi php-curl belum terinstall pada komputer mas
kalo untuk linux bisa dengan menginstallnya

perintah untuk linux debian dan turunanya
`sudo apt install php8.1-curl` untuk 8.1 adalah versi php yang sudah di gunakan saat ini

untuk kasus pada window bisa mengaktifkan nya di php.ini 
untuk contoh pengguna examp

buka php.ini
aktifkan extensi 
`extension=curl `

pastikan extensi php8.1-curl pada folder ext ada

lalu pastitkan pada baris 
`;curl.cainfo = `
sudah terdapat isi yang mengarah ke sertifikast ssl nya
biasnaya berisikan lengkap seperti di bawah ini
`curl.cainfo="C:\xampp\apache\bin\curl-ca-bundle.crt"`

ok maaf dan terimakasih sudah menggunakan packages bpjs bridging versi php

**Comment by alfikridotname** [comment]
terima kasih atas jawabannya mas
utk versi php sayang menggunakan 8.1

dan saya tidak menggunakan xampp ...

**Comment by virusphp** [comment]
untuk php bisa menggunakan versi php 7 kak 
saya mencoba selalu update dengan versi php agar tidak ketinggalan dan menjadikan suatu masalah di masa mendatang

**Comment by alfikridotname** [comment]
tetapi masih error mas
array:2 [ // app\Http\Controllers\Vclaim\SepController.php:27
  "metaData" => array:2 [
    "code" => 0
    "message" => "cURL error 60: SSL certificate problem: unable to get local issuer certificate (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://apijkn-dev.bpjs-kesehatan.go.id/vclaim-rest-dev/referensi/faskes/ikur/1"
  ]
  "response" => null
]

itu response nya mas...biasanya saya tambah http dengan withOptions(['verify=>false']) 

ttpi saya tidak tahu yang mana saya mau edit...soalnya mas pakai guzzle http

**Comment by virusphp** [comment]
Selamat pagi mas 

tetap semangat dalam berkarya

silahkan pake packages yang sudah saya update mas tanpa menggunakan guzzle

sudah tersedia 

dan tutorial penggunaan 
dengan php dan laravel akan di update kemungkinan minggu mendatang

![image](https://user-images.githubusercontent.com/17744762/196850952-96937ec5-52be-4179-b02c-c602a7bd270f.png)
gambar di atas adalah contoh menggunakan php native

dan sukses 
menghasilkan response sebagai berikut
![image](https://user-images.githubusercontent.com/17744762/196851040-c7e70324-a199-444d-8c2d-f7de5ce21e83.png)

**Comment by alfikridotname** [comment]
selamat pagi juga mas..

terima kasih mas...sekarang udah aman mas... semoga makin bagus packagenya  mas..

**Comment by virusphp** [comment]
Terimakasih kembali
